export const vars = {
    INCREASE_ITEM: 'INCREASE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEMS: 'CLEAR_ITEMS',
    LOADING: 'LOADING',
    DISPLAY_ITEMS: 'DISPLAY_ITEMS'
}